apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: cluster-gitops
  namespace: gitops
spec:
  server:
    host: bamoe-cluster-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud
    ingress:
      enabled: false
    route: 
      enabled: true
