apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-bamoe-kogito-travel

resources:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-kogito-travel
- target:
    kind: AppProject
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-kogito-travel
    - op: replace
      path: /spec/description
      value: BAMOE Services Project
    - op: replace
      path: /spec/sourceNamespaces/0
      value: app-bamoe-kogito-travel
    - op: replace
      path: /spec/destinations/0/namespace
      value: app-bamoe-kogito-travel
