apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: bamoe-keycloak
spec:
  targetNamespaces:
    - bamoe-keycloak
  upgradeStrategy: Default
--- 
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: keycloak-operator 
  namespace: bamoe-keycloak
spec: 
  channel: fast 
  name: keycloak-operator 
  source: community-operators
  sourceNamespace: openshift-marketplace