apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-bamoe-services

resources:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-services
- target:
    kind: AppProject
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-services
    - op: replace
      path: /spec/description
      value: BAMOE Services Project
    - op: replace
      path: /spec/sourceNamespaces/0
      value: app-bamoe-services
    - op: replace
      path: /spec/destinations/0/namespace
      value: app-bamoe-services
