apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: cluster-gitops
  namespace: gitops
spec:
  sourceNamespaces:
    - app-*
  repo:
    replicas: 1
  server:
    replicas: 1
    host: argocd.example.com