apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: argocd-operator.v0.12.0
  namespace: openshift-operators 
spec: 
  channel: alpha 
  version: 0.12.0
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace